"""
export.py — Report Generation for NewsBot 2.0

This module exports analysis results into readable report files
(text, markdown, or JSON format).

Think of it like a printer that takes your analysis results
and turns them into a professional document.
"""

import json
import os
from datetime import datetime


class ReportExporter:
    """
    Exports NewsBot analysis results to files.

    Supported formats:
    - JSON  → machine-readable data file
    - Markdown (.md) → human-readable formatted report
    - Plain text (.txt) → simple text report

    Example:
        exporter = ReportExporter(output_dir="data/results")
        exporter.export_json(analysis_results, "my_report")
        exporter.export_markdown(analysis_results, "my_report")
    """

    def __init__(self, output_dir="data/results"):
        """
        Args:
            output_dir: Folder where reports will be saved
        """
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    def _get_timestamp(self):
        """Return current timestamp as a string."""
        return datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    def _get_filepath(self, filename, extension):
        """Build the full file path."""
        clean_name = filename.replace(" ", "_").lower()
        return os.path.join(self.output_dir, f"{clean_name}.{extension}")

    def export_json(self, data, filename="report"):
        """
        Export data as a JSON file.

        Args:
            data: Dictionary of analysis results
            filename: Name for the output file (without extension)

        Returns:
            Path to the saved file
        """
        filepath = self._get_filepath(filename, "json")

        export_data = {
            "generated_at": self._get_timestamp(),
            "system": "NewsBot 2.0",
            "data": data
        }

        try:
            with open(filepath, "w", encoding="utf-8") as f:
                json.dump(export_data, f, indent=2, ensure_ascii=False, default=str)
            print(f"✅ JSON report saved to {filepath}")
            return filepath
        except Exception as e:
            print(f"❌ Failed to save JSON: {e}")
            return None

    def export_markdown(self, analysis_results, filename="report", title="NewsBot 2.0 Analysis Report"):
        """
        Export analysis results as a formatted Markdown report.

        Args:
            analysis_results: Dictionary of analysis results
            filename: Name for the output file (without extension)
            title: Title for the report

        Returns:
            Path to the saved file
        """
        filepath = self._get_filepath(filename, "md")

        lines = [
            f"# {title}",
            f"",
            f"**Generated:** {self._get_timestamp()}",
            f"**System:** NewsBot 2.0",
            f"",
            f"---",
            f""
        ]

        # Write each section of the results
        for section, content in analysis_results.items():
            lines.append(f"## {section.replace('_', ' ').title()}")
            lines.append("")

            if isinstance(content, dict):
                for key, value in content.items():
                    lines.append(f"- **{key}:** {value}")
            elif isinstance(content, list):
                for item in content:
                    lines.append(f"- {item}")
            else:
                lines.append(str(content))

            lines.append("")

        lines.append("---")
        lines.append("*Report generated by NewsBot 2.0 — ITAI-2373 NLP Final Project*")

        try:
            with open(filepath, "w", encoding="utf-8") as f:
                f.write("\n".join(lines))
            print(f"✅ Markdown report saved to {filepath}")
            return filepath
        except Exception as e:
            print(f"❌ Failed to save Markdown: {e}")
            return None

    def export_text(self, analysis_results, filename="report", title="NewsBot 2.0 Report"):
        """
        Export analysis results as a plain text file.

        Args:
            analysis_results: Dictionary of analysis results
            filename: Name for the output file (without extension)
            title: Title for the report

        Returns:
            Path to the saved file
        """
        filepath = self._get_filepath(filename, "txt")

        lines = [
            "=" * 60,
            f"  {title}",
            "=" * 60,
            f"Generated: {self._get_timestamp()}",
            f"System: NewsBot 2.0",
            "",
        ]

        for section, content in analysis_results.items():
            lines.append(f"\n[{section.upper()}]")
            lines.append("-" * 40)

            if isinstance(content, dict):
                for key, value in content.items():
                    lines.append(f"  {key}: {value}")
            elif isinstance(content, list):
                for item in content:
                    lines.append(f"  - {item}")
            else:
                lines.append(f"  {content}")

        lines.append("\n" + "=" * 60)
        lines.append("End of Report")
        lines.append("=" * 60)

        try:
            with open(filepath, "w", encoding="utf-8") as f:
                f.write("\n".join(lines))
            print(f"✅ Text report saved to {filepath}")
            return filepath
        except Exception as e:
            print(f"❌ Failed to save text report: {e}")
            return None

    def list_reports(self):
        """List all reports in the output directory."""
        try:
            files = os.listdir(self.output_dir)
            if not files:
                print("No reports found.")
                return []
            print(f"Reports in '{self.output_dir}':")
            for f in files:
                print(f"  - {f}")
            return files
        except Exception as e:
            print(f"Error listing reports: {e}")
            return []
